### ISSUE TITLE
wordpress implementation

### ISSUE THREAD

**Issue by lucafolin** [dagababaev/Synology_SSO_integration#2]
Very interesting scripts !
Please could you help me to implement this script in a wordpress site hosted in synology nas ?
So I can access my wordpress site using my synology SSO service.

**Comment by dagababaev** [comment]
Sorry, I am not working with WP and don't know how auth working there (no time to learn now). You can host this script on your synology or any vps, but integration with WP you need make by yourself

**Comment by eocula** [comment]
Hi @lucafolin , have you ever found a solution for this ? As I have the same question : I'm trying to use these scripts to authenticate users, visiting a WordPress-website hosted on my Synology-NAS, on my Synology SSO-Service.

It's working partly : 
(1) when I visit the website, it's asking the credentials
(2) I'm using the credentials from a Synology-NAS-user
(3) the user get's authenticated (as I can see in DSM that this user has been logged in)
(4) but after the login, I get a web-page saying "<LOCAL_HOST> redirected you too many times ; and "ERR_TOO_MANY_REDIRECTS"

So, 2 questions : 
1. @dagababaev : are you sure the last line in config.php is correct ? Being : //define('REDIRECT_URI', '<mySite>/my/SSO_Oauth.php');   -- PS : I placed the SSO_Oauth.php file in that "my" subfolder
2. @lucafolin : have you ever made this working ?

Many thanks !

**Comment by lucafolin** [comment]
Sorry eocula but I wasn't able to implement SSO with wordpress hosted on my NAS. I have the same error.
L.
